spring.application.name=fraud-auth-api
spring.datasource.url=jdbc:postgresql://localhost:5432/fraud_db
spring.datasource.username=authapi
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true